services:
  marzneshin:
    # Веха 5: сменить на brotherhugo/marzneshin, когда панель на Docker Hub.
    image: dawsh/marzneshin:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzneshin:/var/lib/marzneshin

  marznode:
    image: brotherhugo/marznode:v0.1.0
    restart: always
    network_mode: host
    environment:
      SERVICE_ADDRESS: "127.0.0.1"
      INSECURE: "True"
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SING_BOX_ENABLED: "True"
      SING_BOX_EXECUTABLE_PATH: "/usr/local/bin/sing-box"
      SING_BOX_CONFIG_PATH: "/var/lib/marznode/sing-box.json"
      SING_BOX_RESTART_ON_FAILURE: "True"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"
    volumes:
      - /var/lib/marznode:/var/lib/marznode
