name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Lint with pylint
        run: |
          pylint --exit-zero "$(git ls-files '*.py')"

      - name: black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./app"
          use_pyproject: true