name: Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'app/dashboard/package-lock.json'
  
      - name: Install dependencies
        run: npm install
        working-directory: ./app/dashboard/
  
      - name: Lint Dashboard
        run: npm run lint
        working-directory: ./app/dashboard/

      - name: Build Dashboard
        run: npm run build --if-present -- --outDir dist --base '/dashboard/'
        working-directory: ./app/dashboard/
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dawsh/marzneshin:latest
            dawsh/marzneshin:${{github.ref_name}}
