name: Docker image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
          cache-dependency-path: dashboard/pnpm-lock.yaml

      - name: Build dashboard
        working-directory: dashboard
        env:
          VITE_BASE_API: /api/
          VITE_LATEST_APP_VERSION: ${{ github.ref_name }}
        run: |
          pnpm install --frozen-lockfile
          pnpm build --base '/dashboard/'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            brotherhugo/marzneshin:latest
            brotherhugo/marzneshin:${{ github.ref_name }}
