name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Release with release-please
        uses: google-github-actions/release-please-action@v2
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
